### ISSUE TITLE
Keeping your fork Updated with Latest Changes

### ISSUE THREAD

**Issue by Keerti-Gautam** [Keerti-Gautam/learning#1]
Needs a thorough explanation on how to keep your fork up to date with the latest changes, preferably with written commands.

**Comment by Keerti-Gautam** [comment]
Issue Resolved with commit d40434983e8e7cf3afa14f561afa96fb4eaad68a: Issue #1 Resolved

**Comment by sakshamsaxena** [comment]
[This](https://help.github.com/articles/closing-issues-via-commit-messages/) might come in handy next time ! :smile: More power to you !
